[package]
name = "todo"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.4.0", features = ["derive"] }
shell-words = "1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
